# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10.16.0

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run: yarn install
      - run:
          name: Run tests
          command: yarn test
  build:
    <<: *defaults
    steps:
      - checkout
      - run: yarn install
      - run:
          name: Build output
          command: yarn build

      - persist_to_workspace:
          root: ~/build
          paths: *
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/build
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  build-workflow:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - build:
          requires:
            - test
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
